### ISSUE TITLE
Defining how each issue error message is displayed

### ISSUE THREAD

**Issue by DM-TPX-Delivery** [digital-land/submit#165]
## Design direction

When a issue affects every row (eg values are missing from the same field in every row) then the issues should be rolled up into a single issue (eg "`<column name>` is missing values")

We should also show column missing issues in this view, which don't exist in the issues table

## Current design
![Image](https://github.com/user-attachments/assets/ad2b4dc1-1a4a-40e2-a9cd-25b0f32b5862)

## Tech direction

# Tech Considerations
the issues table: https://datasette.planning.data.gov.uk/digital-land/issue has the info we need to generate the messages. the two key fields in this are 
- value: contains the value of the issue field, sometimes with some accompanying data
- message: contains a message describing what this issue is

## Tasks
- [ ] Content review - Gwen (Data Design)
- [ ] User Testing - w/c 12th Aug
- [ ] Discuss with George how to implement

**Comment by Darren-CheckPlanningData** [comment]
@alextea Based on Deepdive feedback and general conversations design for this should be revisited. Looking at Alpha phase outputs/BFL design

**Comment by CharliePatterson** [comment]
Let's break this down into more concrete asks - I've spun up one ticket to capture the part around grouping issues when the dataset is missing a column here: https://github.com/digital-land/submit.planning.data.gov.uk/issues/306

I don't think there's any other specific things being highlighted in this ticket, unless I'm missing something?
