### ISSUE TITLE
Design & Prototype dataset issues page

### ISSUE THREAD

**Issue by Darren-CheckPlanningData** [digital-land/submit#172]
### Problem statement

Users don’t currently have a way to see what errors exist in their data so don’t know what they need to fix

### User story

> As an LPA user I need to know what issues are present and need fixing in my datasets so that I know what I need to do in order to fix them

### Acceptance criteria

- [ ] - User can see the issues highlighted in context
- [ ] - Error messages are clear and have steps on how to resolve the issues
- [ ] - There is guidance on how to update the dataset so the fixes are processed by the platform
- [ ] - There are alternative designs showing a card view and a table view

### Current Design:

![Image](https://github.com/user-attachments/assets/fe859ebd-9012-4ca5-b1e9-b823adda790c)

### Task

- [ ] Discussion with data management how to display columns
- [ ] Creating the prototype
- [ ] What questions to ask in testing sessions with LPAs related to this prototype

### Supporting artefacts:
Jira user has provided feedback on ticket [DLSD-1007](https://dluhcdigital.atlassian.net/jira/servicedesk/projects/DLSD/queues/custom/35/DLSD-1007):

Good afternoon 

Following the planning data drop-in session earlier this week, some feedback on the data checking tool. 

It would be useful if the found errors are easy to navigate to as currently I am having to flick through 72 pages to find the errors from the TPO dataset I uploaded:

![Image](https://github.com/user-attachments/assets/2a86869f-8928-4caa-8865-b2f87cf464a1)

Maybe the ones that have errored could display at the start of the list so it is clear to see which ones they are.

**Comment by Darren-CheckPlanningData** [comment]
Jira response to user:
Darren Matthews - 30/08/2024

God afternoon Sam

Thank you for this valuable feedback. The issue you have raised is something our development team are currently addressing.  We are in the design phase for this work but will swiftly move into prototyping and implementing a solution. Would you be open to taking part in user testing session(s) on this, once we are ready to test? 

 

Best regards

Planning Data Development Team

**Comment by CharliePatterson** [comment]
Given we have an MVP of this out there, we should close this and open up a more specific story to cover the next iteration of this work.
