### ISSUE TITLE
Deep-linking into the check tool

### ISSUE THREAD

**Issue by CharliePatterson** [digital-land/submit#307]
## Context:

- The check tool previously existed as a standalone service, but has now been integrated into a larger user journey.
- In the previous incarnation it made sense to ask the user to select which dataset they wished to run through the check tool, however in this iteration the user is arriving at the tool via selecting a specific dataset.
- As such, we should be able to already determine which type of dataset they are checking, and so remove the necessity for them to have to tell us which dataset they are checking.
- This has come up in user testing, where users are confused as to why we're asking them to tell us which dataset they're checking when they just clicked on a link for a specific dataset.

## Acceptance criteria:

- As a data provider, when I click through to the check tool form values should be populated based on the page I was previously viewing. for example, viewing a specific dataset
- When navigating to the check tool, if the previously viewed page causes form fields to be populated, the user should start the process from a later page in the check tool. i.e. no need to see the dataset page if the dataset field has automatically been populated

### Tech approach:
When using check tool use redirect so users do not need to set LPA and data set viewed, using last viewed.
Look at how to use the session that is started when you click 'start now'
Option for users to change mind - e.g. using breadcrumb links (look at separating this out to a new ticket)

## Task list

- [ ] Create route, that expects any number of params representing form fields
- [ ] update any links to check tool to use this new hidden link
- [ ]  add controller method behind this link that reads url params and creates a session then sends user to the relevant next page
- [ ] Test against acceptance criteria and acceptance tests

**Comment by CharliePatterson** [comment]
Awaiting design input from: https://github.com/digital-land/submit/issues/384

**Comment by rosado** [comment]
To be clear: the goal to populate/fill the data (where possible) when user clicks the link marked by the red arrow? @CharliePatterson 

![Image](https://github.com/user-attachments/assets/900bf150-1725-4df4-93bc-c07b74ef97b3)

**Comment by CharliePatterson** [comment]
With regards to the UX-related question as to what the intended behaviour is:

- When the user enters the check tool, they no longer see the start page (as per https://github.com/digital-land/submit/issues/389)
- The dataset page is also skipped, and the user is sent to the relevant next page (the 'upload method' page: https://submit.planning.data.gov.uk/check/upload-method)

@alextea can you weigh in on this?

**Comment by rosado** [comment]
@alextea Should both links (1 and 2 on screenshot) on the "get-started" page be "deep links"? 

![Image](https://github.com/user-attachments/assets/cdf6851a-0ffc-4094-b2b9-3422c22b7d4d)
