### ISSUE TITLE
Enable the check tool to accept two coordinate geometries

### ISSUE THREAD

**Issue by Darren-CheckPlanningData** [digital-land/submit#310]
## Context:

- Brownfield land datasets contain multiple geometry columns - geoX/geoY - (as does the transport node dataset), whereas the check tool only supports point data.
- If an LPA were to run their brownfield land dataset through the check tool it wouldn't display their data on the map correctly.
- This won't be the case for any further datasets in future, so we don't need to build a scalable solution for this, as we just need to solve it for these two datasets.

## Acceptance criteria:

- As a data provider, when I am using the check tool to check datasets that use multiple geometry columns (e.g. Brownfield land), the map renders correctly and shows me the data I've inputted via the file

## Implementation details:

- We should look in the column field log in the frontend to determine the geometry columns.
- We should look in this order/priority: geom -> point -> geoXgeoY

## Tasks:

- [x] Look at what plug-in if any could do this for us - task too trivial to pull 3rd party code
- [ ] Add an architectural decision record (ADR) to record the decision.
- [x] Infrastructure to investigate how they can support implementation. - infra team did the work, see my [comment](https://github.com/digital-land/submit/issues/310#issuecomment-2338500203), infra PR: https://github.com/digital-land/async-request-backend/pull/41

### Supporting artefacts:

- Spike: [#289](https://github.com/digital-land/submit.planning.data.gov.uk/issues/289#issuecomment-2291213946)

**Comment by rosado** [comment]
Shouldn't the list presented under '/check/dataset' also contain 'brownfield-land' option?

**Comment by rosado** [comment]
The async request API seem to only return the newly added 'transformed_row' entries when we pass `dataset=brownlfield-land` to '/requests/:id/response-details' which we currently, don't do. Do we need a 'brownfield-land' option on the get started page?

Since we don't do that, I just create `POINT(${GeoX} ${GeoY})` atm.

**Comment by CharliePatterson** [comment]
There are a couple of other things we need to do before telling people they can use this to check their brownfield land data: https://github.com/digital-land/submit/issues/379

Also, we're looking to remove that start page, so it depends on timing.
