### ISSUE TITLE
Dataset details page

### ISSUE THREAD

**Issue by CharliePatterson** [digital-land/submit#311]
## Context:

- Data providers cannot see how a specific dataset for a particular LPA has been processed by the platform.
- Currently data is shown as aggregated up, which serves one need for data consumers. But how can users delve into problems with a specific dataset for a particular provider?

### Outcome:

LPAs can see the data they’ve submitted to the platform

### Strategic goal:

Improving data quality

### Implementation:

A dataset details page that shows the LPA the data they’ve provided. Ship something lightweight / tightly scoped, and iterate on it.

[User needs map](https://app.mural.co/t/mhclg2837/m/mhclg2837/1724840653903/bbaca85b511dfe09cf913a7da7e8bb9398d2ddab?wid=0-1725275836710&sender=u799a8d48c5284c2a3d7b5169)

## Acceptance criteria:

- [x] As a data provider, when I've submitted my dataset to the platform and it has been processed by the data management team, then I can see the data that I've provided.
- [x] A design for a dataset with single endpoint
- [x] A design for a dataset with multiple endpoints
- [ ] A design for a collection of datasets
- [ ] Designs include navigation to the tasklist, to view the data and to the check and submit flows

## Questions:

- ???

## Tasks:

- Design the page.

**Comment by CharliePatterson** [comment]
Thanks @alextea 🙏 

Can you please create versions of these for each iteration? 

1. Current page + map
2. Summary/overview table
3. New navigation between dataset details, tasklist and issues page
4. Viewing whole dataset

We need the first one for this ticket: https://github.com/digital-land/submit/issues/387

**Comment by DilwoarH** [comment]
@alextea @CharliePatterson 

The following details do not work for a cluster of datasets:
- Data URL
- Data URL last accessed
- Data URL last updated
- Source documentation

**Reason**: This is because each dataset will contain X number of entries - each with their own Data URL and source documentation - we do not seem to have one for the whole dataset for an organisation (please point me to the correct place if I'm mistaken).

Could you also let me know how the following values would be calculated:
- The total expected number of fields supplied
- What are fields matched vs unmatched?
- I am using the number of unique entities are a way to calculate the number of records - is this correct?

**Comment by alextea** [comment]
@DilwoarH do you have an example of which datasets will be affected? There is a [design for datasets with multiple endpoints](https://private-user-images.githubusercontent.com/523014/364793552-4dcdcc05-aed7-4221-9672-252dbd58e2e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0NzYyNTAsIm5iZiI6MTcyNjQ3NTk1MCwicGF0aCI6Ii81MjMwMTQvMzY0NzkzNTUyLTRkY2RjYzA1LWFlZDctNDIyMS05NjcyLTI1MmRiZDU4ZTJlNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNlQwODM5MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYTQ3ZWZhMjIyOGU2OTRjOTAzODI1YzE4NjdhM2RmMGI4YTJhNDMxOGIzMmI0YjE3MTQ4MDVhOThjNzU4ZWI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6bOHybkXAEu1UGJ2HkwqpGPHDBWYtPon87NPpNGhssU)

The fields supplied and matched can be calculated using the performance table. You can see an example in the config manager: https://config-manager-prototype.herokuapp.com/reporting/odp-summary/conformance @greg-slater should be able to help you get those figures.

**Comment by DilwoarH** [comment]
> @DilwoarH do you have an example of which datasets will be affected? There is a [design for datasets with multiple endpoints](https://private-user-images.githubusercontent.com/523014/364793552-4dcdcc05-aed7-4221-9672-252dbd58e2e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY0NzYyNTAsIm5iZiI6MTcyNjQ3NTk1MCwicGF0aCI6Ii81MjMwMTQvMzY0NzkzNTUyLTRkY2RjYzA1LWFlZDctNDIyMS05NjcyLTI1MmRiZDU4ZTJlNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxNlQwODM5MTBaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYTQ3ZWZhMjIyOGU2OTRjOTAzODI1YzE4NjdhM2RmMGI4YTJhNDMxOGIzMmI0YjE3MTQ4MDVhOThjNzU4ZWI3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6bOHybkXAEu1UGJ2HkwqpGPHDBWYtPon87NPpNGhssU)
> 
> The fields supplied and matched can be calculated using the performance table. You can see an example in the config manager: https://config-manager-prototype.herokuapp.com/reporting/odp-summary/conformance @greg-slater should be able to help you get those figures.

Thanks Alex - I will have a look at the repo and get that information transferred over.

**Comment by DilwoarH** [comment]
FYI:
- We had to turn off displaying the maps on following datasets: Tree, Tree Preservation Order, Tree Preservation Zone
- The reason why we had to do this was because the database was taking too long to respond and the page request was timing out - therefore left the user with a failed error message
- Spoke to the infrastructure team and they suggested that we use the GeoJSON API from the search ie. https://www.planning.data.gov.uk/entity.geojson?dataset=article-4-direction-area&geometry_curie=statistical-geography:E09000003
- There are some caveats with this - they suggested there may be slight difference in the data between there
- We will need to dig in deeper to understand this a bit more but I am currently looking at implementing the GeoJSON which seems a like a more sensible thing to do.
