### ISSUE TITLE
Bug: content and design fixes for live service

### ISSUE THREAD

**Issue by alextea** [digital-land/submit#348]
## Start page

![Image](https://github.com/user-attachments/assets/90301e9e-0ab9-4710-a35e-0c6313c2e863)

- [ ] GOV.UK logo and service title should link to `/manage` (needs fixing site wide)
- [ ] stray ellipsis needs removing (needs fixing site wide)
- [ ] "Explore the topic" section should be removed from related navigation

## Organisation finder

- [ ] organisation list includes orgs that definitely aren't LPAs (including Wikimedia Foundaton, HM Land Registry, ONS)

## Organisation dashboard

![Image](https://github.com/user-attachments/assets/a9cebfeb-8d0a-46f9-933f-a47e3b6a5e89)

![Image](https://github.com/user-attachments/assets/6bcba2f3-4668-4a71-a4fe-0c085a9993a0)

- [ ] Org name in breadcrumb needs correct capitalisation
- [ ] Dataset list should be alphabetically ordered
- [ ] "Not submitted" tag should be grey
- [ ] "Warning" tag should be removed — content and design not finished
- [ ] "Live" tag shows alongside text showing issues exist / either the tag or the text is wrong
- [ ] When there's only a single issue the text should be "There is 1 issue in this dataset"

## Task list

![Image](https://github.com/user-attachments/assets/27366d8c-b384-4a8b-920e-1566d1b6c9ef)

- [ ] "Live" tag on warning items
- [ ] Warning items should be removed — content and design not finished

## Dataset issue details

![Image](https://github.com/user-attachments/assets/fb897e5a-153b-4772-9c0c-dd5b4cbb9144)

- [ ] Page should show first entry with an error by default
- [ ] "entry" should be capitalised in summary card header (eg "Entry: 1")
- [ ] Pagination is missing

## Get started

![Image](https://github.com/user-attachments/assets/a1b3adeb-4c0f-4fbe-b55c-ad70b4bcaaa2)

- [ ] Breadcrumb title should be "Get started" (incorrect capitalisation)
- [ ] Bullet list in content needs `govuk-list govuk-list--bullet` classes

**Comment by DilwoarH** [comment]
FYI - Ellipsis has been fixed, waiting on release https://github.com/digital-land/submit/pull/342

**Comment by DilwoarH** [comment]
*Note for when we take this into development*:
Split tickets into smaller grouped chunks

Suggested split:
- Content change
- Incorrect tag labelling
- Implement pagination
- Other style changes

Alternatively, additional split could be done on a page by page basis.

**Comment by CharliePatterson** [comment]
Broken this out into the following tickets:

- https://github.com/digital-land/submit/issues/358
- https://github.com/digital-land/submit/issues/357
- https://github.com/digital-land/submit/issues/356
- https://github.com/digital-land/submit/issues/355
- https://github.com/digital-land/submit/issues/354
- https://github.com/digital-land/submit/issues/303
- https://github.com/digital-land/submit/issues/304
- https://github.com/digital-land/submit/issues/359
