### ISSUE TITLE
Handle maps with invalid points more gracefully

### ISSUE THREAD

**Issue by DilwoarH** [digital-land/submit#364]
## What

Maps displaying undesirably when invalid points / no points.

<img width="1110" alt="Screenshot 2024-09-02 at 12 52 34 PM" src="https://github.com/user-attachments/assets/fcde8f30-a855-44a4-ab23-0023ac2c2f02">

## Background

When a map has invalid points / spatial data, it does not render these points - the behaviour that we observe is that the map is display but at the centre of the world (in the middle of the ocean).

## Potential solutions

- Center map to the UK by default (example: https://codepen.io/DilwoarH/pen/bGPmwym)
- Don't display the map if there are no valid points
- Display an error message when we do not receive correct data from the request API
- Validate data points / spatial data using Zod or similar object schema checkers to ensure it's correct

## Steps to reproduce the issue

1. Go to https://check.planning.data.gov.uk/ and click on start
2. Select `Tree preservation order dataset`
3. Select URL
4. Use `https://www.ashford.gov.uk/media/uuqnswra/tpo_spatial_22_07_24.csv`
5. View map below table

## Acceptance criteria

- [ ] Map shows UK by default
- [ ] Display error message if data is invalid
- [ ] Validate data points

## Tasks

- [ ] PM to decide what is the desired behaviour
- [ ] Dev to implement changes
- [ ] Test new behaviour with users (optional)

## Supporting artefacts
- [Video of debugging issue on Tree dataset](https://www.loom.com/share/ef4651f53e5644cdb9f7af2afdb9332d)

## Impact
How many people are affected (04/11/2024)
- Difficult to gage

What part of the process is it impacting
- Check your data

Is it preventing people from completing an action or a minor annoyance
- Big impact as users may perceive no points on the map as issues with their data
- LPAs have raised this as an issue via Jira

**Comment by alextea** [comment]
A future enhancement would be to centre on the LPA's boundary once the check service is integrated into the dashboard flow

**Comment by CharliePatterson** [comment]
Thanks @DilwoarH 🙌 this needs some design/UX thinking on the best approach for how this fails gracefully.

My two cents would be to hide the map and show an error message to explain what's going on, so that it reduces confusion.

**Comment by neilfwar** [comment]
already done on previous completed ticket - duplicate
