### ISSUE TITLE
Coordinate requests for usability research sessions across the project  

### ISSUE THREAD

**Issue by MJFaucherFolie** [digital-land/submit#375]
**Problem statement**
1) LPAs are inundated with uncoordinated requests from various stakeholders, both within the project and external authorities. This mass amount of communication makes it challenging for LPAs to engage with us.

2) There is a small pool of users and a lot of requests for user research activities 

**User story**
As an: LPA
I want: clear, simple obligations and opportunities with respect to usability testing 
So that: I can easily manage and respond to requests

As an: User researcher 
I want: access to relevant user groups for surveys, usability testing, workshops etc.  
So that: can discover user pain points and understand user behaviour 

**Tasks**
- [x] Create a single slack channel for Design Researcher across the project 
- [x] A meeting with Community Managers and Design Researchers across the project 
- [ ] Further actions to come from that meeting

**Comment by jimmytidey** [comment]
New version of the planning document: https://docs.google.com/document/d/12yV9V7-RWWg8btZn7XNUjAZsrXq6ZwRExbKilppjHQE/edit#heading=h.eqoetppgduft
