### ISSUE TITLE
Streamline & improve the check tool user experience

### ISSUE THREAD

**Issue by CharliePatterson** [digital-land/submit#381]
## Context:

- The Check tool was previously a standalone service, but has since been integrated with a number of other things, to create a more unified service.
- However, the end-to-end service journey is still a bit disjointed, and lacks coherence.
- We have identified a number of opportunities to streamline and improve the user experience of the check tool:
  - **Removing the start page:** This is now redundant, as people should have sufficient context from the previous page in the journey. Additionally, users rarely read start pages, making them extra redundant.
  - **Deep-linking:** Given the new user journey, the second step in the flow of the check tool is also now redundant, as it's an unnecessary step, since they would've arrived on the tool via a specific dataset page.
  - **Completion page:** The current experience at the end of the check tool flow tells the user to publish their data and then email the endpoint URL to us. This needs to connect to the rest of the user journey.
  - **Context throughout experience:** As the user navigates through the tool, there's no context to tell them which dataset they're checking.

## The work:

Design:

- [x] https://github.com/digital-land/submit/issues/384

Engineering:

- [ ] https://github.com/digital-land/submit/issues/389
- [x] https://github.com/digital-land/submit/issues/307
- [x] https://github.com/digital-land/submit/issues/383
- [x] https://github.com/digital-land/submit/issues/390
