### ISSUE TITLE
Improve dataset issues page experience

### ISSUE THREAD

**Issue by CharliePatterson** [digital-land/submit#382]
## Context:

- The LPA dashboard signposts data quality issues with submitted datasets, and helps LPAs to understand what these are, and how to improve the quality of their data by addressing these.
- The dataset tasklist page and issues pages detail the specifics of the issues, but these can sometimes be difficult to understand.

## Outcomes:

The core goal here is to help LPAs to easily understand the issues with the datasets they’ve provided and know how to fix them.

The specific outcomes to achieve through this epic are:

- When a dataset contains the same issue across multiple entities, these are grouped so that it's easier to understand.
- When a dataset is missing a column, the user is informed of this, rather than being shown the same issue across all entities.
- LPAs can view all issues aggregated in a single table, rather than having to view each individual record at a time.
- LPAs are able to visually check the data for any geospatial datasets they've provided is correct.

## The work:

**Design:**

- [ ] https://github.com/digital-land/submit/issues/485

**Engineering:**

- [x] https://github.com/digital-land/submit/issues/388
- [x] https://github.com/digital-land/submit/issues/306
- [ ] Grouping many issues (ticket pending)
