### ISSUE TITLE
Initial iterations to the start page

### ISSUE THREAD

**Issue by paris-dp** [digital-land/submit#391]
**Context:**   
At present the start page doesn’t set the context of the service, or let the user know what to expect within the service. 

**Outcome:** 
User story: As a data provider, when I enter the service, I have the information I need to understand the service and what is expected of me. 

**The work:**
- [x] Workshop session to explore approach from a product perspective with Charlie including discussion about key iterations that can be made prior to the 18th, and selection of a layout for initial iteration [Workshop: Start page content and layout · Issue #393 · digital-land/submit (github.com)](https://github.com/digital-land/submit/issues/393)
- [x] Alex and Gwen to explore the journey flow and layout constraints. Exploration of the journey flow and layout constraints · Issue #394 · digital-land/submit (github.com)
- [ ] Complete a content review/gap analysis when considering user needs. [Start page/guidance content review and gap analysis · Issue #395 · digital-land/submit (github.com)](https://github.com/digital-land/submit/issues/395)
- [x] Improve the current content to better explain the programme and expectations of what will be within the service. Particularly that we index data that is collected nightly.
- [ ] Creation of further epic tickets to iterate the design and content of the start page

**Comment by paris-dp** [comment]
Message received from Charlie re proposed content:

**What does this page need to convey?**

 **_What the platform does:_**
- Centralising planning and housing data for England
- Ensuring consistency / conformance to specifications
- Open data
- Seeking to enable reform of planning

**_How it works:_**
- LPAs own and publish the data
- We act as a central index

**_What this service will do:_**
Guide you through the process of:
- Preparing and checking your data
- How to publish it so that we can index your data and it’ll appear on the platform
-----
**Proposed content:**
The planning data platform centralises planning and housing data for England, ensuring consistency and access to this data. Making this data freely available plays a key part in reforming the planning system.

Use this service to submit or update your Local Planning Authority’s data to the planning data platform.

The service will guide you through the following steps:

1. Prepare your data and check it meets the specifications
2. Publish your data to your local authority website
3. Share the URL for the data to enable the platform to access and index it

**Comment by paris-dp** [comment]
reopened issue as it contains activities that have not yet been completed
