### ISSUE TITLE
Play data back to LPAs: Dataset details page MVP

### ISSUE THREAD

**Issue by CharliePatterson** [digital-land/submit#403]
## Context:

- When data providers have submitted their datasets, they will want to know that it has been indexed correctly by the platform, and will want to check a number of factors.
- To enable this, we want to play back a summary/overview of key information about their data to them.
- We also want to play back their geospatial data in a map so that they can visually check their data is correct.

## The work:

**Design:**

- [x] https://github.com/digital-land/submit/issues/311

**Engineering:**

- [x] https://github.com/digital-land/submit/issues/387
- [x] https://github.com/digital-land/submit/issues/407
