### ISSUE TITLE
Look into 502 errors on sentry

### ISSUE THREAD

**Issue by CharliePatterson** [digital-land/submit#404]
## What

Look into 502 errors caused by https://datasette.planning.data.gov.uk/

## Why

We want to understand and identify any instabilities in the platform so that we can mitigate any performance issues on production.

## Background

Users reported experiencing 502 errors while using datasette.

## Tasks
- [x] Identify trends of when errors occur in sentry
- [x] Use a performance testing tool to simulate traffic
- [x] Write up summary for infrastructure team

## Supporting artefacts

Error list in sentry:
- https://planning-data-platform.sentry.io/discover/results/?cursor=0%3A0%3A1&display=default&field=title&field=event.type&field=project&field=user.display&field=timestamp&interval=1h&name=All+Events&project=4507033205800960&query=%22Request+failed+with+status+code+502%22&sort=-timestamp&statsPeriod=30d&yAxis=count%28%29
- https://planning-data-platform.sentry.io/issues/?project=4507033205800960&query=is%3Aunresolved+issue.priority%3A%5Bhigh%2C+medium%5D+%22Request+failed+with+status+code+502%22&referrer=issue-list&statsPeriod=90d

Useful tools for performance testing:
- https://locust.io/ - used in https://github.com/digital-land/async-request-backend/tree/main/performance-test
- https://github.com/six-ddc/plow

**Comment by DilwoarH** [comment]
Analysis documentation:
https://docs.google.com/spreadsheets/d/1-m61RqNbIQJ2KYPrfRz8JEY320vyXdfCMqtxvL4Tk4w/edit?gid=0#gid=0

**Comment by DilwoarH** [comment]
[502 Analysis - Charts.pdf](https://github.com/user-attachments/files/16977491/502.Analysis.-.Charts.pdf)

Analysis above - data can be found here: https://docs.google.com/spreadsheets/d/1-m61RqNbIQJ2KYPrfRz8JEY320vyXdfCMqtxvL4Tk4w/edit?gid=1994576003#gid=1994576003

**Comment by DilwoarH** [comment]
Summary of my analysis attached:
https://docs.google.com/document/d/1GCxQ-YD2geyQRPRuj6jT60GCuUw-tBdXCZx_sKxATzU/edit?usp=sharing

Once reviewed, I will send to infrastructure

**Comment by CharliePatterson** [comment]
Thanks @DilwoarH - some initial thoughts / questions from reading through your analysis:

1. When you say the error count is "relatively low", how are you measuring / gauging that? How does that stack up against, e.g., the total number of page views? Just wondering whether it's more useful to measure errors in relation to another metric, so we can assess what the level of impact is.
2. Following on from the above, what's a reasonable/acceptable level of errors?
3. Are the errors spread across various pages, or concentrated on different page types?
4. How do we figure out what the thing(s) are that are responsible for causing these errors? Can we be more forensic with that, or is it more a case of trying the different mitigation strategies you've outlined, and seeing what works?

**Comment by gmatchett** [comment]
@DilwoarH @CharliePatterson @neilfwar 

I spoke with the team about this, and also requested access to the doc so we have a record of this message
The issues between 12-2 are known and are causes by limitations within Datasette.  Similar issues occur between  6 -8.
We are looking to address these in Q3 and form part of our OKRs relating to performance.
One area which we need to understand is how many of these errors are impacting real users.  This is linked to the request for the robots.txt, card . [https://github.com/digital-land/submit/issues/318](url)  What is now needed is for the robot.txt to be introduced and the analysis to be redone to see how much is caused by scanners/crawlers

**Comment by DilwoarH** [comment]
> Thanks @DilwoarH - some initial thoughts / questions from reading through your analysis:
> 
> 1. When you say the error count is "relatively low", how are you measuring / gauging that? How does that stack up against, e.g., the total number of page views? Just wondering whether it's more useful to measure errors in relation to another metric, so we can assess what the level of impact is.

I think yes this would be better against page views, unfortunately, this wasn't available to me at the time.

> 2. Following on from the above, what's a reasonable/acceptable level of errors?

Ideally we should be in the single digits or new errors rather than repeated same errors

> 3. Are the errors spread across various pages, or concentrated on different page types?

It was mainly caused by the Datasette service but there are other pages which cause this too.

Link to sentry: https://planning-data-platform.sentry.io/issues/?environment=production&project=4507033205800960&query=502&referrer=issue-list&statsPeriod=90d

> 4. How do we figure out what the thing(s) are that are responsible for causing these errors? Can we be more forensic with that, or is it more a case of trying the different mitigation strategies you've outlined, and seeing what works?

The sentry link above will show where in the code the errors occurred.

**Comment by DilwoarH** [comment]
> @DilwoarH @CharliePatterson @neilfwar
> 
> I spoke with the team about this, and also requested access to the doc so we have a record of this message The issues between 12-2 are known and are causes by limitations within Datasette. Similar issues occur between 6 -8. We are looking to address these in Q3 and form part of our OKRs relating to performance. One area which we need to understand is how many of these errors are impacting real users. This is linked to the request for the robots.txt, card . [https://github.com/digital-land/submit/issues/318](url) What is now needed is for the robot.txt to be introduced and the analysis to be redone to see how much is caused by scanners/crawlers

Thanks @gmatchett - I will work with the team to get the robot.txt changes in.

I will close this issue for now as the investigation has been concluded.
