### ISSUE TITLE
Add issues table component to issues details page

### ISSUE THREAD

**Issue by CharliePatterson** [digital-land/submit#423]
## Context:

- The current implementation of the dataset issues page is that we're playing issues back to users on a per-entity / per-record basis, meaning that users have to click through each entity/record to view the details of the issue.
- This isn't a great user experience when the user is faced with a high volume of issues.
- A better experience would be to display this data back to them in an aggregated format, in a table.
- The intention is to re-use the component from the check tool, so that we don't have multiple versions of the same thing floating around, and only have to maintain styles in one place: https://github.com/digital-land/submit/issues/421

## UX:

- The table view will be the default view for the issues details page.
- Users will navigate to the issues entity page from the issues table. The table should include a link to the entity-level view, to each specific entity.
- The table view the same as the current entity-level view, except that the entity table is replaced with the aggregated table.
- Each view should have their own pagination as well (might not always need it shown if all rows fit on a single page).
- In terms of column ordering in the table: reference should show first, and ideally the rest should be in alphabetical order (though we may want to cut this from the scope depending on the level of complexity).
- To navigate back to the table view from the entity-level view, we will use a back link above the summary (see: https://github.com/digital-land/submit/issues/406#issuecomment-2344033857).

## Acceptance criteria:

- As a data provider, when I'm on the dataset issues page, I see a table that shows me an aggregated view of all the records with the issue that I'm viewing.
- As a data provider, when I'm on the dataset issues page, the table contains a link to each individual entity that takes me to the entity-level view.
- As a data provider, when I'm on the entity-level view of the dataset issues page, I see a link to take me back to the table view.

## Tasks:

- [x] write middleware's
- [x] make a basic template 
- [x] Populate error summary
- [x] populate breadcrumb links
- [x] have the reference's link through to the entity views
- [x] ~sort the columns to spec order~ (rendering in specification order)
- [x] duplicate reference issues should skip to entry view
- [x] don't show issues where there's no entity (except those to do with reference)
- [x] add pagination
- [x] add valibot schema
- [x] move test code for moved middlewares
- [ ] ~add test code for new template issueTable.html~ (going to pick this up in a new ticket as its complicated to mock the table params, and the dataview template also needs testing)
- [x] add code to test middleware in dataview.middleware.js
  - [x] getDataRange
- [x] add test code for middleware in common.middleware.js
  - [x] createPaginationTemplateParams
  - [x] show404IfPageNumberNotInRange
  - [x] FilterOutIssuesToMostRecent
  - [x] removeIssuesThatHaveBeenFixed
  - [x] addFieldMappingsToIssue
- [x] add test code for middleware in issueTable.middleware.js
  - [x] getDataRange
  - [x] prepareTableParams
  - [x] getErrorSummaryItems
  - [x] prepareTemplateParams
  - [x] notIssueHasEntity
  - [x] issueTypeAndFieldShouldRedirect
  - [x] redirectToEntityView
  - [x] getIssueTable
  - [x] show404IfPageNotInRange

# Content review tasks
- [x] On the pages that go to the record view, the summary box is empty https://submit-pr-691.herokuapp.com/organisations/local-authority:LBH/tree/missing%20value/point/entry
- [ ] table view summary showing column level error while task list is not
  - this is correct on the table view, but incorrect on the tasklist. will be resolved when updating the task list to look at all active resources/entities 
- [x] article 4 lambeth showing data on table but not on entity
  - this was due to a bug, have fixed in this PR
  - this page is also only looking at the latest active resource, ideally this should look at the entitiy similar to how the table view works
    - Alex has a new design for this page, so might just hold of to do it in there

## Problems:

> 
> ### duplicate entity references provided by different organisations
> data management are looking at this one
> 
> --------------------------------------------------------------
> 
> ### Any issue causing an entry not to become an entity
> we can't really show it on the table as it doesn't have any data, only the issues!
> I think we want a different view for this, I suggest we skip the table view and go directly to an individual task view
> Also, we should only pull these issues from the latest resource, as we don't know if they have been fixed in a later resource
> for example: https://submit.planning.data.gov.uk/organisations/local-authority:LBH/listed-building-outline
> 
> Now: skip to entry view
> Later: updated design indicating the resource and line number where this is happening
> 
> --------------------------------------------------------------
> 
> ### Duplicate entity references provided by the same organisation
> for this type of task, instead of having a page with for example three 'duplicate reference issues' we go to a page that has one issue stating something along the lines of: 'you have 3 entries all with the same reference across lines and 4, 20, 24'
> for examlpe here: https://submit-pr-691.herokuapp.com/organisations/local-authority:LBH/listed-building-outline
> 
> Now: skip to entry view
> Later: new design for each duplicate, showing the processed entity and indicating the resource and rows of the duplicates
> 
> --------------------------------------------------------------
> 
> ### Any other issue not on an entry that isn't an entity not causing the entity to be made
> I don't think we should be showing right now, its really complicated especially when some some of these issue types and field pairs are on an entity and some are not, after they fix the reference issue. then any other issues will show up
> http://localhost:5000/organisations/local-authority:LBH/article-4-direction-area
> This one becomes even more problematic when a previously uploaded entity without a reference has other errors and then the org fixes them by reuploading the file but deleting the rows. 
> for example, [lambeth has no article-4-direction areas](https://www.planning.data.gov.uk/entity/?dataset=article-4-direction-area&entry_date_day=&entry_date_month=&organisation_entity=192) but they previously tried to upload some, but didn't provide references. so we ended up with [these issues](http://localhost:5000/organisations/local-authority:LBH/article-4-direction-area) that can never be resolved
> 
> Now: don't show these issues
> 
> --------------------------------------------------------------
> 
> ### What do we do when an issue doesn't exist in an earlier resource, but it does in a later resource??
> So looking at [this](https://submit-pr-691.herokuapp.com/organisations/local-authority:MAV/brownfield-land/missing%20value/SiteNameAddress) we can see missing-value issues on fields that have values. this is because in a previous resource the values were there, but in their latest resource they have removed that value for some reason???
> looking at the [data](https://datasette.planning.data.gov.uk/digital-land?sql=select+*+from+resource+r%0D%0ALEFT+JOIN+resource_organisation+ro+ON+r.resource+%3D+ro.resource%0D%0ALEFT+JOIN+resource_dataset+rd+ON+r.resource+%3D+rd.resource%0D%0AWHERE+rd.dataset+%3D+%27brownfield-land%27%0D%0AAND+ro.organisation+%3D+%27local-authority%3AMAV%27%0D%0AAND+r.end_date+%3D+%27%27%0D%0AORDER+BY+r.start_date) basically, in row 3 the values are present but row 4 they are not 
> 
> Now: show issue for now with normal message
> Later: update messages to indicate this is occurring in your latest resource
> 
> --------------------------------------------------------------
> 
> ### The task list and overview is currently gathering issues that have been resolved and are no longer relevant
> this can be problematic as in a few edge cases issues that has been fixed by a newer resource are still being used i.e. https://submit.planning.data.gov.uk/organisations/local-authority:MAV/brownfield-land
> 
> Now: Deploy as normal, then start work on other pages to bring into sync with this one
>  
> 
> 
>

**Comment by GeorgeGoodall-GovUk** [comment]
Moving back to sprint backlog and picking up #407 as we want to prioritise that

cc: @CharliePatterson

**Comment by GeorgeGoodall-GovUk** [comment]
After talking with Owen around all this, there's some changes that need to be made.

# the primary issue is the confusion between an entity and and entry.
## An Entity: 
refers to data that has made it on to the platform, this data might have some fields missing. but will at the least have a reference.

## An Entry:
refers to a row of data uploaded by someone. this might not make it on to the platform, or it might?


## Issues are logged against entries
Issues are logged against entries, this causes complexity as we are trying to show issues against entities and to do this involves linking entities back to entries


## How do we surface the data
We could 
- grab issues and then find the entries that match those issues. 
- grab entries and then map this issues onto those entries. 

The first approach might miss out data provided by other organizations, it also might not show us valid entities
The second approach wouldn't show us entries that never made it on the platform to become entities


## My proposition
- for now i think we should update all queries on submit to look for entities first, then grab issues associated with those entities.
-  - this does mean that entries that never became entities wont show up on submit. aka entities with reference errors. but for now i think this is a good stepping stone until we work out those issues

**Comment by GeorgeGoodall-GovUk** [comment]
Another caveat I've just discovered from this.

sometimes we have an issue against an active resource, but there's a valid value against that field and entity? not currently sure if this is coming from another active resource from that lpa, or another lpa. do we not show this issue?

**Comment by GeorgeGoodall-GovUk** [comment]
I'm going to put this ticket on pause as linking issues to entities is a real challenge with the current database setup. for example. even getting the count of references, for a given resource times out -_-

https://datasette.planning.data.gov.uk/tree?sql=select+count%28*%29+from+fact+f%0D%0ALEFT+JOIN+fact_resource+fr+ON+f.fact+%3D+fr.fact%0D%0AWHERE+fr.resource+%3D+%272a8277852c2a6378d8b93d8bcfffe6e64bd1b73916918329c8b7c63837b131d8%27%0D%0AAND+f.field+%3D+%27reference%27

**Comment by GeorgeGoodall-GovUk** [comment]
Working on [this mural](https://app.mural.co/t/mhclg2837/m/mhclg2837/1729683204212/db6515486e181846d6145a0260ca0cc4199b1b84?sender=u070ebbe6992cd47a04ab8098) to try and outline what we need of the performance db / api

**Comment by Ben-Hodgkiss** [comment]
@CharliePatterson & @neilfwar - just to say that we believe we've done the infrastructure changes for this ticket now so have closed our corresponding ticket. If you do need anything from us, let me know.

**Comment by CharliePatterson** [comment]
Thanks @Ben-Hodgkiss 🙏

**Comment by GeorgeGoodall-GovUk** [comment]
More potential problems: 
we are getting the data from the entities table. however Im not sure if i can trust the entities table anymore as...

entity 6100323 article-4-direction is owned by entity 192: 
https://datasette.planning.data.gov.uk/article-4-direction/entity?_sort=entity&entity__exact=6100323


> Org Entity 192 is lambeth: https://datasette.planning.data.gov.uk/digital-land/organisation?_sort=organisation&entity__exact=192
> 
> Entity 6100323 has a document-url of: https://www.sandwell.gov.uk/downloads/file/1614/west-bromwich-high-street-conservation-area-article-4-direction
> 
> Which comes from this fact:
> https://datasette.planning.data.gov.uk/article-4-direction?sql=select+*+from+fact+f%0D%0ALEFT+JOIN+fact_resource+fr+ON+f.fact+%3D+fr.fact%0D%0Awhere+%22entity%22+%3D+%3Ap0+and+%22field%22+%3D+%3Ap1+order+by+fact+limit+101&p0=6100323&p1=document-url
> 
> Which comes from this resource:
> https://datasette.planning.data.gov.uk/digital-land?sql=select+*%0D%0Afrom+resource+r%0D%0ALEFT+JOIN+resource_organisation+ro+ON+r.resource+%3D+ro.resource++%0D%0Awhere+r.resource+%3D+%3Ap0&p0=2b142efd3bcfe29660a3b912c4f742b9c7ff31c8ca0a02d93c9aa8b60e8e2469
> 
> Which as you can see was supplied by Sandwell Metropolitan Borough Council

Why is an LPA in birmingham supplying data for a borough of london??
is this something to do with the duplicate reference problem?
