### ISSUE TITLE
Table view for displaying dataset issues

### ISSUE THREAD

**Issue by CharliePatterson** [digital-land/submit#424]
## Context:

- The current implementation of the dataset issues page is that we're playing issues back to users on a per-entity / per-record basis, meaning that users have to click through each entity/record to view the details of the issue.
- This isn't a great user experience when the user is faced with a high volume of issues.
- A better experience would be to display this data back to them in an aggregated format, in a table.

## Acceptance criteria:

- As a data provider, when I'm viewing the dataset issues page, I can view the issues presented in a table in an aggregate view.

## Implementation details:

- The intention is to re-use the component from the check tool, so that we don't have multiple versions of the same thing floating around, and only have to maintain styles in one place.
- However, we'll first need to break this out into a separate component.

## The work:

- [x] https://github.com/digital-land/submit/issues/421
- [ ] https://github.com/digital-land/submit/issues/423
- [x] https://github.com/digital-land/submit/issues/422
