### ISSUE TITLE
Integration testing

### ISSUE THREAD

**Issue by CharliePatterson** [digital-land/submit#431]
## Context:

- Integration testing ensures individual components work together seamlessly, catching errors that unit testing may miss. By testing interactions between components, integration testing identifies and fixes issues early, preventing costly rework and delays, and resulting in more reliable and stable software.
- We have been developing these new pages in a hurry to meet imposed deadlines. this had lead us to skip the development of integration tests. these should now be added in so we can maintain are velocity of work and reduce the risk of introducing future bugs

## The work:

- [ ] https://github.com/digital-land/submit/issues/327
- [ ] https://github.com/digital-land/submit/issues/328
- [ ] https://github.com/digital-land/submit/issues/330
- [ ] https://github.com/digital-land/submit/issues/329
- [ ] https://github.com/digital-land/submit/issues/326
- [ ] https://github.com/digital-land/submit/issues/331
