### ISSUE TITLE
Understand FAQs/pain points and utilise as a means of continuous service improvement

### ISSUE THREAD

**Issue by paris-dp** [digital-land/submit#437]
### Problem:
There could be insights that we can surface to improve our service. 

### Acceptance criteria 
**As a user, I want to feel confident that if I am raising a challenge that affects other users, this will be considered a pain point and improvements made, so that I/others can complete the process with more ease in future.** 

### Tasks 

- [ ] Work with community managers and data management to understand FAQs and responses/solutions to those 
- [ ] Work with data management (Greg) to gain a list of known resources for common software issues 
- [ ] Review LPA Slack channel 
- [ ] Review Jira
- [ ] Gain insights from Smartlook
- [ ] Update service/guidance and build this process in to the service process
