### ISSUE TITLE
Standardize status messages

### ISSUE THREAD

**Issue by GeorgeGoodall-GovUk** [digital-land/submit#460]
# Problem statement
Our status messages on the LPA-dashboard could and should be standardized. then stored in the performance database

## Considerations
determining the status of a dataset has many considerations including
- completeness
- endpoint status
- issue of level error rate
- issue of level warning rate
We could and should work with data management to come to conclusions on these

## ToDo:
- [ ] come up with status names and also status states.
- [ ] run them by data management and make sure they agree
- [ ] pass these onto infrastructure, have them implement our agreed state classification logic into the pipeline that generates the performance database
- [ ] update our code to pull status's from the performance database

**Comment by CharliePatterson** [comment]
What's the benefit to doing this?

**Comment by CharliePatterson** [comment]
I'm assuming this will be covered in the API.
