### ISSUE TITLE
Discovery: How do we play back seeded data from alternative sources?

### ISSUE THREAD

**Issue by CharliePatterson** [digital-land/submit#495]
## Context:

- Not all data on the platform has been provided by LPAs: a variety of different sources are used for various datasets (e.g. Historic England).
- Some data on the platform has been scraped from LPAs websites (e.g. Conservation Areas).
- There's a need to play back this data to them, so that they are able to see all data relevant to their jurisdiction, and are aware that it's been provided by a third party source.
- This discovery epic is to start to unpack some of the complexities around playing this data back to LPAs.
- There will be a separate discovery to answer some of the questions around what we want/need LPAs to do about this (e.g. to "sign off" on the data, or tell us if there's something wrong with it).

## Tasks:

- [ ] Figure out discovery questions (e.g. which datasets does this cover?)
- [ ] Answer discovery questions
- [ ] Design exploration
- [ ] Play back designs
