### ISSUE TITLE
Display brownfield land datasets as an option on the LPA dashboard page

### ISSUE THREAD

**Issue by GeorgeGoodall-GovUk** [digital-land/submit#531]
# Task
Add brownfield land into submit

## Acceptance criteria
- [x] brownfield land should be present in:
  - [x] check tool
  - [x] dashboard
- [ ] Check should show the correct result for a check, with all errors except mandatory field errors
- [ ] Dataset overview should show all correct metrics 
- [ ] Dataset overview should display a map with geometric data
- [ ] Dataset tasklist should show if any tasks need completing
- [ ] Issue details should show correct entity information with accompanying issues

## Testing
