### ISSUE TITLE
Review and improve customer touchpoints

### ISSUE THREAD

**Issue by MJFaucherFolie** [digital-land/submit#564]
## Context
- We need to review how we communicate with LPAs across their journey with us
- We need a holistic view of what is being said to them at each touchpoint in the journey
- The goal is to ensure that we're consistent with the way we talk about things and interact with users

## Acceptance Criteria
- Artefact detailing the customer touchpoints
- Examples of engagements we make with users

## Tasks

- [ ] Review and develop separate iteration of the service blueprint for this task
- [ ] Confirm all touch points
- [ ] Identify communications made at each touch point
- [ ] Play back to the team
- [ ] Work with Maddie to refine communication approach 
- [ ] Play back changes to the wider team

## Additional thoughts 
- What _things_ are used to communicate with users (specifications, data quality issues, etc...)

**Comment by MJFaucherFolie** [comment]
Developed a mural board which captures contact points that MHCLG has with LPAs: https://app.mural.co/t/mhclg2837/m/mhclg2837/1729517621123/46c596b8515cd3fc14a9cab9d5d94a5c13d76d3c?sender=u463319bb16378792b5869752

**Comment by maddie-broxup** [comment]
Adding myself as an assignee as I'll work with Paris and MJ on comms approach

**Comment by paris-dp** [comment]
Notes and reflections added to touchpoints map

**Comment by MJFaucherFolie** [comment]
Reviewed notes on mural which Paris and Maddie shared. Updated with answers to questions highlighted and user stories

Also included screenshots of the ODP page for review

**Comment by maddie-broxup** [comment]
Message sent to Swati, Greg and Alex V to understand a bit more about their current emails process, including:

- For the manual ones, do you use a copy and paste template, or are you typing content from scratch each time?
- Does the content ever change depending on the email received, or do you use the same content each time?
- What common questions or confusion do you notice from users after receiving these emails? (If any)
- How do you currently measure the effectiveness of these emails? (If at all)

**Comment by maddie-broxup** [comment]
Received replies to these Qs from data management. @MJFaucherFolie we should discuss what our next steps are :)

**Comment by MJFaucherFolie** [comment]
Drafted [doc](https://docs.google.com/document/d/1DlX_u2L99gpXlNBiboDT0ntP3oGKMTmTuUKTrJwCGR8/edit?tab=t.0#heading=h.xbpl3n72owjp) to support us to progress this ticket forward. Meeting with Maddie set up for Monday to progress further

**Comment by maddie-broxup** [comment]
First drafts - https://docs.google.com/document/d/1DlX_u2L99gpXlNBiboDT0ntP3oGKMTmTuUKTrJwCGR8/edit?usp=sharing

Chatting through these with MJ on Friday and then hopefully we'll be in a position to bring the DM team in :)

**Comment by MJFaucherFolie** [comment]
Reviewed Maddie's fantastic [first draft](https://docs.google.com/document/d/1DlX_u2L99gpXlNBiboDT0ntP3oGKMTmTuUKTrJwCGR8/edit?usp=sharing) and agreed to loop in Charlie, and message the DM team some follow-up questions we have :D

**Comment by maddie-broxup** [comment]
Sent to Charlie for review :)

**Comment by maddie-broxup** [comment]
Reviewed by Charlie and briefly in a design time meeting with Paris, Alex and Gwen too. 

These are now ready to share with the DM team and work out the best way of implementing them

**Comment by maddie-broxup** [comment]
Message sent to Swati, Greg and Alex:

> Hi all 🙂
> 
> I’ve been looking into the email comms mentioned above, and have drafted some proposed updates. The goal here was to make some small adjustments to help make the messaging even clearer, and align with gov best practice.
> 
> I’d love to hear your thoughts - what works, what might need adjustment, or any additional insights you have. If it’s helpful, I’d be happy to discuss this further or collaborate on refining them together.
> 
> There are 4 in total, and they’re quite short, so it shouldn’t take too long to have a scan through. Feel free to add any comments: https://docs.google.com/document/d/1aM82-n8EpE8nH_RYOvexgbR69u5Hj5jvLUUeqDzAPW4/edit?usp=sharing

**Comment by maddie-broxup** [comment]
Additional changes made to service message email after playback of research insights - https://docs.google.com/document/d/1DlX_u2L99gpXlNBiboDT0ntP3oGKMTmTuUKTrJwCGR8/edit?tab=t.9ntc0apamjlo

**Comment by maddie-broxup** [comment]
Chased Swati today on comments for the email comms and whether we can get the new content into JIRA.

**Comment by maddie-broxup** [comment]
Neil nudged Swati yesterday. Received reply from Swati to say it's on her to do list but isn't a priority right now because it's not a blocker. Discussed with Neil and Charlie that we'll leave this ticket where it is so we don't forget about it. I'll nudge again after Christmas

**Comment by maddie-broxup** [comment]
Moved to backlog as agreed
