### ISSUE TITLE
Iterate error messages displayed to users on platform

### ISSUE THREAD

**Issue by MJFaucherFolie** [digital-land/submit#574]
## Context
- We need to improve the error messages which users of our service see
- To improve the messaging, we must first understand what messages are being shared to users and why

## Acceptance criteria
- Understanding of issues and messages displayed to users 
- Draft changes to messaging 

## Tasks  (BfL focus)
- [ ] Draft spreadsheet filled with issues types **for BfL**
- [ ] Review messaging with @maddie-broxup 
- [ ] Iterate messaging to be more user centred
- [ ] Play back changes to the team 

## Tasks  (ODP datasets)
- [x] Draft spreadsheet filled with issues types for all ODP datasets 
- [x] Collaborate with Data Management in a workshop around issue messaging
- [x] Review messaging with @maddie-broxup 
- [x] Iterate messaging to be more user centred
- [ ] Play back changes to the team 

## Additional thoughts 
- Must find the _single source of truth_ as conversations have highlighted there may be multiple lists of error messaging

**Comment by MJFaucherFolie** [comment]
Drafted spreadsheet which captures issue types and messaging for BfL: https://docs.google.com/spreadsheets/d/1VtHFPYnaAlBODYPkC8E_h9cv3O5irMYtpS7SIW9_Cqo/edit?gid=1806680747#gid=1806680747

Will confirm with members of the project that the datasette contains messages shown to users

**Comment by paris-dp** [comment]
[Workshop completed](https://app.mural.co/t/mhclg2837/m/mhclg2837/1728654025264/16e0efd10d44506f2e66e5b02de469a99692b024?wid=0-1730281420186)- it is felt a wider piece of work to improve testing/messaging is required in the longer term. To continue collaboration between providers and data management

**Comment by maddie-broxup** [comment]
There are 2 things here:

- errors displaying to users when they shouldn't be
- errors not displaying when they should be

Swati is already working with Owen about the first one. 

We agreed I can start mapping the ones that don't exist, which probably should. And involve Greg / Swati in that too. We think this is something we'll chip away at as it's a big task and not a priority for our team this sprint anyway.

Eventually we think it makes sense to use [Datasette](https://datasette.planning.data.gov.uk/digital-land/issue_type) as the source of truth to document everything here already, plus the error message we display to users.

**Comment by alextea** [comment]
Validation messages from the check tool are detailed here: https://github.com/orgs/digital-land/projects/7/views/11?pane=issue&itemId=86341191

**Comment by maddie-broxup** [comment]
The local validation error messages for the check tool are done from a content design POV - https://github.com/orgs/digital-land/projects/7/views/11?pane=issue&itemId=86341191

**Comment by maddie-broxup** [comment]
Walked @paris-dp through the approach I've been taking so far. Scheduled in an hour and a half on Friday to get through as many as we can. Working in this spreadsheet - https://docs.google.com/spreadsheets/d/1Nvr2Hl4RAw_81ggE2V09d4MCR1j7tsxGY-Vy-JeIYX0/edit?usp=sharing

**Comment by maddie-broxup** [comment]
Had a session with Greg to chat through all of this - it's highlighted some important points around consistency of guidance, and also how we might be able to display more of a generic message across data types. E.g. our ideal scenario of more descriptive and useful messages for each field might not be feasible, and we may need more of a general one to cover all requirements. 

We need to follow up with Owen / infra team with some questions too. 

Paris and I to discuss next steps :)

**Comment by maddie-broxup** [comment]
Working with Paris on mapping this in Mural as spreadsheet had some constraints. Will move back into spreadsheet eventually - https://app.mural.co/t/mhclg2837/m/mhclg2837/1734011169645/8bf106fe41725b7b68b8efe71908a075061f9972

Another session today to continue this work

**Comment by paris-dp** [comment]
Discussed in design time- plan for Alex to help us navigate Datasette timing out and work with wider teams around moving this work forward.

**Comment by maddie-broxup** [comment]
1. Alex to help us write queries in Datasette for the remaining issues which currently time out 
2. Paris and I to book in some time with DM (Greg and possibly Swati) to see what we've got and where to go next

**Comment by maddie-broxup** [comment]
Filling in the gaps in the spreadsheet and Mural that I can with the SQL query Alex helped us out with: https://datasette.planning.data.gov.uk/digital-land?sql=select+distinct%28field%29%2C+issue_type+from+issue+where+issue_type+%3D+%3Aissue_type%0D%0A%0D%0A&issue_type=default-value

**Comment by maddie-broxup** [comment]
Paris, Alex and I are meeting with Greg today to continue this work and (hopefully) begin to write some first drafts together.

**Comment by paris-dp** [comment]
Met with Greg again and progressed issue messages- still some message types that have not been covered that are not currently user facing (warnings). Agreed that we would collate this work in to a spreadsheet. 

Maddie and I have now collated this in to a [spreadsheet ](https://docs.google.com/spreadsheets/d/1Nvr2Hl4RAw_81ggE2V09d4MCR1j7tsxGY-Vy-JeIYX0/edit?gid=1363521361#gid=1363521361) which will be shared with Greg on Monday.

**Comment by maddie-broxup** [comment]
Spreadsheet shared with Greg, waiting for review

**Comment by maddie-broxup** [comment]
Signed off by Greg. Will share with Charlie to schedule meeting about where to host the new messages

Spreadsheet here: https://docs.google.com/spreadsheets/d/1Nvr2Hl4RAw_81ggE2V09d4MCR1j7tsxGY-Vy-JeIYX0/edit?usp=sharing

**Comment by maddie-broxup** [comment]
Moved to done as we'll create a new ticket for the subsequent work around storing these messages. @CharliePatterson to set up call for next sprint
