### ISSUE TITLE
Understand the factors behind stale data for BfL

### ISSUE THREAD

**Issue by MJFaucherFolie** [digital-land/submit#575]
## Context
- We need to make it clear to LPAs when their BfL datasets require updating 
- We therefore need to understand what would trigger the need for LPAs to update their BfL data

## Acceptance criteria 
- Clear definitions of stale data, in relation to BfL

## Tasks 
- [x] Connect with the Data Management team to get their input
- [x] Connect with the Policy team to gain their input 
- [ ] Refine notes from the conversations with Data Management and Policy
- [x] Play back findings to the team

## Additional questions
- Should we reach out to LPAs who are currently using the model we want all LPAs to adopt (one endpoint, multiple resources/updates)

**Comment by MJFaucherFolie** [comment]
Greg showcased a new framework to test data quality. Agreed to conduct tests with current BfL to better understand factors which make it stale

**Comment by MJFaucherFolie** [comment]
Shared a note to Eloise

**Comment by MJFaucherFolie** [comment]
Dropped Greg a line to set up a meeting

**Comment by MJFaucherFolie** [comment]
Greg has created and shared a query in the [datasette](https://datasette.planning.data.gov.uk/performance?sql=with+ep_res+as+%28%0D%0ASELECT%0D%0A++organisation%2C%0D%0A++name%2C%0D%0A++endpoint%2C%0D%0A++endpoint_entry_date%2C%0D%0A++resource_start_date%2C%0D%0A++resource%0D%0AFROM%0D%0A++reporting_historic_endpoints%0D%0AWHERE%0D%0A++endpoint_end_date+%3D+%22%22%0D%0A++AND+latest_status+%3D+200%0D%0A++AND+pipeline+%3D+%22brownfield-land%22%0D%0A++AND+resource+%21%3D+%22%22%0D%0A++%29%0D%0A++%0D%0ASELECT%0D%0A++organisation%2C+name%2C%0D%0A++ROUND%28%28julianday%28date%28%27now%27%29%29+-+julianday%28min%28resource_start_date%29%29%29+%2F+365%2C+1%29++as+oldest_resource_age_years%2C%0D%0A++ROUND%28%28julianday%28date%28%27now%27%29%29+-+julianday%28max%28resource_start_date%29%29%29+%2F+365%2C+1%29++as+newest_resource_age_years%2C%0D%0A++count%28distinct+endpoint%29+as+n_unique_endpoints%2C%0D%0A++count%28distinct+resource%29+as+n_unique_resources%0D%0AFROM+ep_res%0D%0AGROUP+BY+1%2C+2) which helps us to identify:
- The volume of endpoints LPAs have supplied for BfL
- The time in which they update their BfL andpoints (when was the resource last updated)

**Comment by MJFaucherFolie** [comment]
Policy have confirmed that LPAs are required to **review** their data once per year, not _submit_. This means that the LPAs can follow the model of one endpoint and multiple resources/updates, and confirming that their BfL register is up to date, even if it was _submitted_ a few years back.

Full response bellow: 

> **What would trigger the need for an LPA to update their BfL register:** They are required by regulations to review the BfL register once per year. Any updates that are made would likely be in response to a change in the criteria of that land as set out in regulation 4 of the BfL regulations (e.g. the development is no longer considered achievable within 15 years).

> **What would constitute as stale BfL data:** As part of the review process they identify sites which would no longer meet the criteria of BfL as specified in regulation 4 of the BfL regs (e.g.) if the land is suitable for residential development, size etc.).

> **If an LPA was to submit the same BfL register two years in a row, would this be frowned upon:** The regulations only require you to review it so if the LPAs considers that it's up to date that would be the position. I don't think the department scrutinises registers that much at the moment, but with the emphasis that is now on BfL this may change.

**Comment by MJFaucherFolie** [comment]
Ticket has been used to develop artefacts featured in #614
