### ISSUE TITLE
Data quality notification Round #2

### ISSUE THREAD

**Issue by MJFaucherFolie** [digital-land/submit#580]
## Context
- The first round of service messaging was a success
- The second round will include an increased number of LPAs to reach out to

## Acceptance criteria
- Email content approved (dependent on ticket #578)
- List of LPAs to email, updated weekly
- Email schedule confirmed

## Tasks 
- [x] Identify the best way to collect and update emails (link in with Community Management team)
- [x] Iterate the CRM google spreadsheet based on feedback shared for first prototype
- [x] Plan an email schedule for a four-week time-period 
- [x] Secure approval from Charlie 
- [x] Launch campaign

## Dates of campaign
- [x] 02 December
- [ ] 11 December

**Comment by MJFaucherFolie** [comment]
Had a conversation with @paris-dp and @CharliePatterson:

Goal:
- Launch 2 service messages before the end of the year

Next steps:
- Charlie will create UTM formula in Google Sheets and investigate if we can mail merge (between a google doc and google sheet dynamically)
- Paris will reach out to Dami (Product Manager) to understand if we can gain access to their CRM system
- MJ will record a video outlining the process to send service messages

**Comment by paris-dp** [comment]
Message sent to Dami- due to leave on Monday and Tuesday included Charlie in this message

**Comment by paris-dp** [comment]
Met with Dami and Stanley to discuss: Next steps to draft our need with Neil- meeting booked for tomorrow. 

Data quality emails for this round drafted.

**Comment by paris-dp** [comment]
Met with Neil and Charlie. Informed that Dami has requested that we create a user need and informed that at present we can not pull contact details from the CRM. [Notes from our meeting](https://app.mural.co/t/mhclg2837/m/mhclg2837/1728654025264/16e0efd10d44506f2e66e5b02de469a99692b024?wid=0-1732891800357) Plan: follow up meeting with Dami and share user needs of the providers team and context around this.

**Comment by MJFaucherFolie** [comment]
@paris-dp has populated a document which now contains draft emails for each LPA who has data quality issues (many thanks!!)
@MJFaucherFolie has created a spreadsheet (based on the document Paris populated) so it is digestible via Gov.Notify
@MJFaucherFolie has sourced 138 emails for 25 LPAs
@maddie-broxup has created a template in Gov.Notify 
![image](https://github.com/user-attachments/assets/576a645a-d8a8-4505-9300-8df3b34c497b)

**Comment by paris-dp** [comment]
I had a follow up meeting with Dami (CRM PM). Talked through the notes from our call and agreed to write our needs up in to a document. This will be used to input into a wider statement of work which will include needs from all teams and therefore we may need to continue with manually creating and sending service emails. 

Draft of needs shared with Neil, Charlie and MJ for feedback before sharing with Dami.

**Comment by paris-dp** [comment]
[User needs](https://docs.google.com/document/d/1H4dQa3eKdRyDXhD-m6PSjCnQk7ErBYcqNpHRvTMbuZs/edit?usp=drive_link) shared with Dami

**Comment by MJFaucherFolie** [comment]
Drafted second round of emails ([spreadsheet](https://docs.google.com/spreadsheets/d/1B2ty48P9YlRoY4WuO2TCRMmRY9-M_ywU95vO2OPCSnY/edit?gid=1329204017#gid=1329204017) / [doc](https://docs.google.com/document/d/1yb9kJui9g0OxbvtHwfROGF3tQ4E0TlluHwtSzsm9DG0/edit?tab=t.ad6zq6awqab6))

Will check over on Monday to ensure any _optional_ issues (I.E - descriptions which can be blank) are identified.

**Comment by MJFaucherFolie** [comment]
On Jan 15th, Charlie, Maddie and MJ reviewed the impact of the Service Notification email. The [spreadsheet](https://docs.google.com/spreadsheets/d/1B2ty48P9YlRoY4WuO2TCRMmRY9-M_ywU95vO2OPCSnY/edit?gid=1659160675#gid=1659160675) was reviewed and notes were captured on the [mural](https://app.mural.co/t/mhclg2837/m/mhclg2837/1728654025264/16e0efd10d44506f2e66e5b02de469a99692b024?wid=0-1736938227544).

As a summary: We sent 128 emails to reach 25 LPAs. 15 (60%) of the LPAs access their Dashboard. Of the LPAs we contacted, 9 (36%) fixed their issues
