### ISSUE TITLE
Review of the endpoint overview section of the dataset details page

### ISSUE THREAD

**Issue by MJFaucherFolie** [digital-land/submit#583]
## Context
- The dataset details page contains information about the dataset, but research and conversations has highlighted the need to further iterate this page
- We are unsure if all the elements on the page is necessary, if there are elements to add which will add value, and if there are incorrect details on the page

## Acceptance criteria 
- We understand the useful elements on the dataset details page and which new elements which would add value to the page
- We are aware of elements on the page which are correct and incorrect

## Tasks
- [ ] Review existing research highlighting elements that would add value to the page
- [ ] Set up and have a conversation with Data Management and understand from their perspective what elements add value and what is missing 
- [ ] Refine research and play it back to the team

**Comment by CharliePatterson** [comment]
Covering this as part of https://github.com/digital-land/submit/issues/619
