### ISSUE TITLE
Drivers behind addressing data quality issues

### ISSUE THREAD

**Issue by MJFaucherFolie** [digital-land/submit#585]
## Context
- We conducted a service messaging prototype and of the 10 LPAs who we engaged in, 2 fixed at least one data quality issue
- We need to understand why they fixed those issues highlighted

## Acceptance criteria 
- We have a clear understanding of why the LPAs fixed their data quality issues

## Tasks
- [x] Draft intro email
- [x] Send email to relevant LPAs
- [x] Phone North Lincolnshire on the 30th and take notes
- [x] Meet Gateshead on 11th Nov and take notes
- [x] Meet Barnet on 12th Nov and take notes
- [x] Meet Canterbury on 13th Nov and take notes
- [x] Refine notes 
- [ ] Work with Adetutu to synthesise findings
- [ ] Playback findings to the team

**Comment by MJFaucherFolie** [comment]
[Drafted emails for the LPA](https://docs.google.com/document/d/12J13ZFF0mg_kQzBNodg--3hXTi_ZFTQoJQ4NMs3Ux6w/edit?tab=t.0) and sent emails to relevant LPAs

**Comment by MJFaucherFolie** [comment]
Had a phone call with North Lincolnshire on the 1st November and [refined notes based on conversation](https://docs.google.com/document/d/1r0VBrMpeMngdj9F0xd9DzsjU4pL3oNNBX2a6hkWxS74/edit?tab=t.0).

Key points
- Subject line could improve if we added in _context_ such as 'Planning Data Project'. This would help him prioritise the email over the others in the inbox
- The _red_ and _green_ (emojis) helped him identify what needed attention promptly
- He forwarded the email to his spital team and did not see that the additional elements of the service message until promoted (signing up additional receipts)
- The LPA has a customer inbox email address which would have read the content and forwarded the service message to his team.
- Other service messages he receives lack the level of detail included in the service message and also gate important information behind a log-in, which makes it challenging for his team to take action

**Comment by MJFaucherFolie** [comment]
Secured meeting with Barnet for 12/11/2024

**Comment by MJFaucherFolie** [comment]
Secured meeting with Gateshead for 11/11/2024

**Comment by MJFaucherFolie** [comment]
Secured meeting with Canterbury on 13/11/2024

**Comment by MJFaucherFolie** [comment]
Met with Gateshead. [Drafted notes](https://docs.google.com/document/d/1rp0T4UzufgTwALp4L7DyFq4wyPYekWHr-IJwgousa80/edit?tab=t.w1xwx7r5f5y7#heading=h.bioxhphi965) from the discussion. 

Key points:
- Emails are welcomed, but Slack is their preference. Emails from external sources are always flagged and content can't be read until message is opened
- Can we explore ways to update them of data quality issues via data services they currently use (ESRI)
- Willing to set up a dedicated inbox to ensure emails are triaged to right people (in his absence)
- The email address (DigitalLandTeam@...) didn't make much sense to him until he read the content of the message (PlanningData@... would be better)
- Service message was shared with relevant members of the team and used as part of internal meetings to scope next steps

**Comment by MJFaucherFolie** [comment]
Met with Barnet on 12th November. [Drafted notes](https://docs.google.com/document/d/1t_1w5yzpo21cGziVHiygTgE9Q3qf9QiCPAV-DDRz-Bs/edit?tab=t.fl6uabjqcpho) from the discussion.

Key points:

- They export their data monthly and replace their data files stored on their Open Data platform (OpenBarnet)
- If emails are not detailed with issue descriptions, it will be ignored
- He did not scroll beyond the fold, but would have used the pause function
- If specification changes were included in service messages, it would add value

**Comment by MJFaucherFolie** [comment]
Met with Canterbury. [Drafted notes](https://docs.google.com/document/d/1HsEWDe_eV9XJtAa4lIWj2VyUMSkJfwrGa2APAA4zrWY/edit?tab=t.135m50rqo9yv) from discussion.

Key points:

- Without context, the email was a bit worrying as they did not know if it was a cyber attack (they experienced cyber issues in the past)
- Links which direct to a government website helped reassure the LPA, but would have welcomed an intro email explaining what to expect
- The email helped them access their dashboard, so she shared it with her team to let them know what issues needed fixing, but believe another team working on HMLR fixed the issues due to data cleansing
- Believes the message was sent to the right person, but recommends sending it to the team inbox
-  Messages are similar to NUAR and GEO places

**Comment by MJFaucherFolie** [comment]
Set up meeting to synthesise on Monday 18th

**Comment by MJFaucherFolie** [comment]
Synthesised the interviews I conducted and Adetutu reviewed them: https://app.mural.co/t/mhclg2837/m/mhclg2837/1731920985941/e8182a692056dd1e99cc34e6b0c4eb35ee664adb

Drafted a deck which I will review with Adetutu: https://docs.google.com/presentation/d/1BeHBJCh2x81T8Tj1_QIbrn4XUS2VdTw8V0hGCioc9Pc/edit#slide=id.g2eff037075c_1_152
