### ISSUE TITLE
Document the process for LPAs to submit BfL

### ISSUE THREAD

**Issue by MJFaucherFolie** [digital-land/submit#646]
## Context
Following on from ticket #631, having an understanding of the process LPAs go through to submit BfL is key if we are going to try and encourage them to adopt the model of continuously update their data and not review annually

## Acceptance criteria
Clear understanding, from the users perspective, of how their BfL register and submit it

## Tasks

- [ ] Identify LPAs who are willing to share their approach to submitting BfL data
- [ ] Document their approach 
- [ ] Play back to the team

**Comment by MJFaucherFolie** [comment]
> Some questions I think we should be asking:
> 
> * how/where do they store their brownfield land data?
>   
>   * if they are using a GIS tool is this the same as their other datasets?
>   * is the data available via an endpoint?
> * what format do they keep the geospatial data in?
> * how do they update it?
> * what steps do they go through to prepare the CSV for brownfield land?

Agreed! 

Regarding completing this work, it'll likely happen in the new year, as every LPA I've spoken to has said that their planning application team do not have time for meetings at the mo 😞
