### ISSUE TITLE
Automating service messaging

### ISSUE THREAD

**Issue by MJFaucherFolie** [digital-land/submit#647]
## Context
- Based on ticket #576 , we understand the requirements to successfully automate service messaging
- We will automating the process, end to end

## Acceptance criteria
- Automate the service messaging process

## Dependencies 
- [x] Secure new content for service messaging from Maddie / ticket #564

# Tasks based on [user story map](https://app.mural.co/t/mhclg2837/m/mhclg2837/1730108333408/e35d809eaeff9cae4cc861743d8337393ae4a7eb) & write-up of [Three Amigos session](https://docs.google.com/document/d/1CdZCyUmHtOYmA6rGu09p-ALD_NuD57Q0Oba3ePpejZ0/edit?tab=t.0#heading=h.evdfy7a2mmxf)

### Assemble list of LPAs who need Service Messages and relevant information 
- [x] #672
- [ ] Ensure the content matches refinements made by @maddie-broxup in ticket #578 

#### **Key outcome**
- Automated process to identify LPAs who have Data Quality issues and collate information about the data quality issues

---

### Automate securing and sending emails#
- [x] #673
- [ ] #674
- [x] #675
- [ ] Develop a way to automatically assemble email lists and content of emails
- [ ] Develop a mechanism to automatically generate UTM links that direct users to their LPAs dashboard
- [ ] Automate sending emails to LPAs with data quality issues

#### **Key outcomes**
- Automatically gather relevant LPA email addresses 
- Automate sending emails to relevant LPAs that feature UTM links and data quality information

---

### Automate process of logging information 
- [ ] Develop a mechanism to capture the number of LPAs who have data quality issues every week 

#### **Key outcome**
- Automatically store data quality issues on a week-by-week basis

---
### Integrate method to sign up for service 
- [ ] #676
- [ ] #677
- [ ] Identify best place in the user journey (on the dashboard) to enable people to sign up for service messaging

#### **Key outcome**
- Enable users of the platform to sign-up to data quality messaging

---

## Future features

- [ ] non-LPAs signing up for service messaging

## Tasks 
- [x] #665

**Comment by MJFaucherFolie** [comment]
Spike::

subscriptions - more difficult 
list of emails - send to these emails 
Figure out where to store the list
Google sheet - simplest - but talk with infra as they have vested interest 
Should we use the CRM system which community management has


Sign up:
Spike - non-LPA people who sign up for messages, how can they take themselves off it

MS forms
Audit MS forms

**Comment by MJFaucherFolie** [comment]
SCRIPT

https://submit-summary.onrender.com/
 
Code is here: https://github.com/DilwoarH/submit-summary
Organisation Summary

**Comment by MJFaucherFolie** [comment]
test
