### ISSUE TITLE
Data not displaying on the map

### ISSUE THREAD

**Issue by MJFaucherFolie** [digital-land/submit#651]
## Context
LPAs such as [Ashford](https://submit.planning.data.gov.uk/check/results/oXLy83RBDzUtMzUGmrfdy6/0) and [Torbay](https://submit.planning.data.gov.uk/check/results/RN4TwVAuhUtSzn8HjMzNBY/0) don't see their point data on the map.

Work from ticket #449 helped us discover that there were a few issues with the data validation:
- Point data formatting isn't correctly validated
- Geo X and Geo Y columns are not correctly validated

LPAs have submitted geojson with the polygons in the OSGB36 co-ordinate reference system. Check is returning an empty map and the WKT field in the table (on check) shows the co-ordinates are still in OSGB, which could be why they’re not showing on the map as that’s not valid WKT.

The pipeline does handle this and will convert it to WGS84, so it’s strange that that’s not being displayed on the Check tool.

![Image](https://github.com/user-attachments/assets/037fc75f-b61d-42bb-8d55-0df8bd3d5f4b)

## Jira
12 November 2024 -
https://mhclgdigital.atlassian.net/issues/DLSD-1093?jql=labels%20%3D%20%22check-tool-issue%22%20ORDER%20BY%20status%20ASC

## Tasks 
- [x] Connect with Infra team
- [x] Connect with Data Management
- [ ] Agree an approach moving forward

**Comment by MJFaucherFolie** [comment]
Infra require:

- the incoming file that the LPA submitted
Torbay: https://www.torbay.gov.uk/services/spatial/GISSpatial/vDLUHC_conservation_area_Publish/geometryquerygeojson
Ashford: TBC

- the incoming data points that are being converted incorrectly
- how those data points are converted in the API and to what
- conversely, what you expect it to be converted

**Comment by Ben-Hodgkiss** [comment]
@MJFaucherFolie - just wondering if we've gotten any of the requirements above so we can get this in the backlog?

**Comment by DilwoarH** [comment]
@MJFaucherFolie @Ben-Hodgkiss 

I've recorded a video; we need to investigate further from our end first. However, there is some issue with the easting and northing coordinate system but we need a test file to understand the problem further.

<div>
    <a href="https://www.loom.com/share/0a98b4a8b7aa490797580d7f47d783ba">
      <p>Data not displaying on the map · Issue #651 · digital-land/submit - 17 December 2024 - Watch Video</p>
    </a>
    <a href="https://www.loom.com/share/0a98b4a8b7aa490797580d7f47d783ba">
      <img style="max-width:300px;" src="https://cdn.loom.com/sessions/thumbnails/0a98b4a8b7aa490797580d7f47d783ba-d0396b6f9e3a7a3c-full-play.gif">
    </a>
  </div>

**Comment by DilwoarH** [comment]
This is now done as we changed our logic to use transformed rows that has valid GEOJSON
