### ISSUE TITLE
Convert insights tracker to new findings tracker (new template to be created)

### ISSUE THREAD

**Issue by Adetutu-Sadiq** [digital-land/submit#698]
- [ ] Create seperate insights tracker for us internally and one for other teams across the service ? No
- [ ] Or post all insights in tracker? - alongside summary of actions we are proposing. 
- [ ] Good to keep it dated (most recent at the top), link to evidence and further information about the insight and action we propose

**Comment by Adetutu-Sadiq** [comment]
This has now been done.

I have created a new live collaborative research repository to this effect 

It can be found here https://docs.google.com/spreadsheets/d/1bGvflNF9pTR6E76sujmGwMFB24B8ZttAGEXtOIw5vxg/edit?usp=sharing
